# Generated by Django 6.0 on 2025-12-24 13:26

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_heading', models.CharField(default='Welcome,', help_text='Main heading text at the top of the dashboard.', max_length=150)),
                ('intro_text', models.TextField(blank=True, default="Here's an overview of your account and quick access to your saved items.", help_text='Displayed under the welcome heading on the dashboard.', null=True)),
                ('support_url', models.URLField(blank=True, help_text='Optional custom URL for the support/contact page. Defaults to /support/.', null=True)),
                ('announcement_bar_text', models.CharField(blank=True, help_text='Optional announcement message shown at the top of the dashboard.', max_length=200, null=True)),
                ('left_title', models.CharField(default='Get In Touch', help_text='Title for the left box on the support page.', max_length=100)),
                ('response_time', models.CharField(default='Within 48 hours (weekdays)', help_text='Displayed response time.', max_length=100)),
                ('support_hours', models.CharField(default='Monday – Friday, 9AM – 4PM GMT', help_text='Displayed support hours.', max_length=100)),
                ('policies_link', models.URLField(blank=True, help_text='Optional link to policies index page.', null=True)),
                ('docs_link', models.URLField(blank=True, help_text='Optional link to documentation page.', null=True)),
                ('help_item_1', models.CharField(blank=True, max_length=150, null=True)),
                ('help_item_2', models.CharField(blank=True, max_length=150, null=True)),
                ('help_item_3', models.CharField(blank=True, max_length=150, null=True)),
                ('help_item_4', models.CharField(blank=True, max_length=150, null=True)),
                ('help_item_5', models.CharField(blank=True, max_length=150, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
        migrations.CreateModel(
            name='GalleryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('body', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Background image for the hero section.', null=True, upload_to='pages/hero/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='New Resources Available!', max_length=200)),
                ('action_text', models.CharField(default="See what's new", max_length=100)),
                ('action_link', models.CharField(blank=True, max_length=200)),
                ('badge_text', models.CharField(default='New', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('template', models.CharField(choices=[('home', 'Homepage'), ('about', 'About'), ('custom', 'Custom Page'), ('gallery', 'Gallery Page')], max_length=20)),
                ('published', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('show_in_navigation', models.BooleanField(default=True, help_text='Show this page in the top navigation bar.')),
                ('show_in_footer', models.BooleanField(default=True, help_text='Show this page in the footer links.')),
                ('menu_order', models.PositiveIntegerField(default=0, help_text='Control the order of this page in the navigation.')),
            ],
            options={
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_mode', models.CharField(choices=[('SHOP', 'Shop Homepage'), ('PAGES', 'Pages Homepage')], default='PAGES', help_text='Choose whether the shop or pages homepage is displayed at the root URL.', max_length=10)),
                ('show_shop_on_homepage', models.BooleanField(default=False, help_text='Show featured products on the homepage.')),
                ('show_blog_on_homepage', models.BooleanField(default=False, help_text='Show the latest 3 blog posts on the homepage.')),
                ('show_gallery_on_homepage', models.BooleanField(default=False, help_text='Show gallery images on the homepage.')),
                ('business_name', models.CharField(default='My Site', help_text='Displayed in the navbar next to the logo.', max_length=150, verbose_name='Business Name')),
                ('logo_image', models.ImageField(blank=True, help_text='Optional logo to display in the navbar beside the business name.', null=True, upload_to='site/logo/', verbose_name='Logo Image')),
                ('site_url', models.URLField(default='https://example.com', help_text='Your full site URL including https:// (e.g., https://mystore.com)', verbose_name='Site URL')),
                ('support_email', models.EmailField(default='hello@example.com', help_text='Email address shown in templates for customer support.', max_length=254, verbose_name='Support Email')),
                ('site_author', models.CharField(blank=True, help_text="Name shown in meta tags and schema markup (e.g., 'Jane Smith' or 'My Company').", max_length=150, verbose_name='Site Author/Owner')),
                ('social_1_name', models.CharField(blank=True, help_text='e.g. LinkedIn', max_length=50, null=True)),
                ('social_1_url', models.URLField(blank=True, null=True)),
                ('social_2_name', models.CharField(blank=True, help_text='e.g. Instagram', max_length=50, null=True)),
                ('social_2_url', models.URLField(blank=True, null=True)),
                ('copyright_text', models.CharField(blank=True, help_text='Optional custom copyright text. Leave blank to auto-generate.', max_length=200)),
                ('default_meta_title', models.CharField(blank=True, help_text='Default meta title for pages without their own.', max_length=150, null=True)),
                ('default_meta_description', models.CharField(blank=True, help_text='Default meta description for pages without their own.', max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages/gallery/')),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='pages/gallery/thumbnails/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.galleryblock')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='galleryblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='pages.page'),
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'Text Block'), ('two_column', 'Two Column'), ('features', 'Features Grid'), ('cta', 'Call to Action'), ('faq', 'FAQ List')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('body', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/sections/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('col_1_body', tinymce.models.HTMLField(blank=True, null=True)),
                ('col_2_body', tinymce.models.HTMLField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ThreeColumnBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('col_1_title', models.CharField(blank=True, max_length=150)),
                ('col_1_image', models.ImageField(blank=True, null=True, upload_to='pages/columns/')),
                ('col_1_body', tinymce.models.HTMLField(blank=True, null=True)),
                ('col_2_title', models.CharField(blank=True, max_length=150)),
                ('col_2_image', models.ImageField(blank=True, null=True, upload_to='pages/columns/')),
                ('col_2_body', tinymce.models.HTMLField(blank=True, null=True)),
                ('col_3_title', models.CharField(blank=True, max_length=150)),
                ('col_3_image', models.ImageField(blank=True, null=True, upload_to='pages/columns/')),
                ('col_3_body', tinymce.models.HTMLField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_columns', to='pages.page')),
            ],
            options={
                'verbose_name': 'Three Column Block',
                'verbose_name_plural': 'Three Column Blocks',
                'ordering': ['order'],
            },
        ),
    ]
