# Generated by Django 6.0 on 2025-12-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryblock',
            options={'ordering': ['order'], 'verbose_name': 'Gallery Block', 'verbose_name_plural': 'GALLERY BLOCKS'},
        ),
        migrations.AlterModelOptions(
            name='pagesection',
            options={'ordering': ['order'], 'verbose_name': 'Page Section', 'verbose_name_plural': 'PAGE SECTIONS'},
        ),
        migrations.AlterModelOptions(
            name='threecolumnblock',
            options={'ordering': ['order'], 'verbose_name': 'Three Column Block', 'verbose_name_plural': 'THREE COLUMN BLOCKS'},
        ),
    ]
