# Generated by Django 6.0 on 2025-12-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_faqblock_faqitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('text', 'Text Block'), ('two_column', 'Two Column'), ('features', 'Features Grid'), ('cta', 'Call to Action')], max_length=50),
        ),
    ]
