# Generated by Django 6.0 on 2025-12-26 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_pagesection_section_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['order'], 'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Sections'},
        ),
        migrations.AddField(
            model_name='hero',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Select which page this hero belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to='pages.page'),
        ),
    ]
