# Generated by Django 5.2.9 on 2025-12-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_hero_options_hero_order_hero_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency_code',
            field=models.CharField(choices=[('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (CA$)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('USD', 'US Dollar ($)')], default='GBP', help_text='Currency code for Stripe payments (e.g., GBP, USD, EUR)', max_length=3, verbose_name='Currency Code'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='currency_symbol',
            field=models.CharField(default='£', help_text='Symbol displayed before prices (e.g., £, $, €)', max_length=5, verbose_name='Currency Symbol'),
        ),
    ]
