# Generated by Django 5.2.9 on 2025-12-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sitesettings_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_title',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this title from the page.'),
        ),
    ]
