# Generated by Django 5.2.9 on 2025-12-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_show_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_embed_html',
            field=models.TextField(blank=True, help_text='Paste the HTML embed code from your email provider (Mailchimp, Mailerlite, ConvertKit, etc.)', verbose_name='Newsletter Signup HTML'),
        ),
    ]
