# Generated by Django 5.2.9 on 2026-01-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_sitesettings_newsletter_embed_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_gallery_on_homepage',
        ),
        migrations.AlterField(
            model_name='galleryblock',
            name='page',
            field=models.ForeignKey(help_text="This gallery will display on the selected page. Use 'order' to control its position relative to other content blocks.", on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='business_name',
            field=models.CharField(default='My eCommerce Site', help_text='Displayed in the navbar next to the logo.', max_length=150, verbose_name='Business Name'),
        ),
    ]
