# Generated by Django 5.2.9 on 2026-01-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_sitesettings_show_gallery_on_homepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_keywords',
            field=models.CharField(blank=True, default='online store, digital products', help_text='Default keywords for SEO', max_length=255, verbose_name='Default Meta Keywords'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_app_id',
            field=models.CharField(blank=True, help_text='Optional Facebook App ID for social features', max_length=50, verbose_name='Facebook App ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Default social sharing image (1200x630px recommended)', null=True, upload_to='site/og/', verbose_name='Default OG Image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_meta_description',
            field=models.CharField(blank=True, default='Welcome to our online store', help_text='Default description for pages without their own (max 160 chars)', max_length=160, verbose_name='Default Meta Description'),
        ),
    ]
