# Generated by Django 5.2.9 on 2026-01-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_sitesettings_default_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#475569', help_text='Accent/highlight color (hex format)', max_length=7, verbose_name='Accent Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='link_color',
            field=models.CharField(default='#2563eb', help_text='Default link color (hex format)', max_length=7, verbose_name='Link Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='link_hover_color',
            field=models.CharField(default='#1d4ed8', help_text='Link color on hover (hex format)', max_length=7, verbose_name='Link Hover Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#0f172a', help_text='Main brand color (hex format, e.g., #0f172a)', max_length=7, verbose_name='Primary Color'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#334155', help_text='Secondary brand color (hex format)', max_length=7, verbose_name='Secondary Color'),
        ),
    ]
