# Generated by Django 5.2.9 on 2026-02-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_sitesettings_accent_color_sitesettings_link_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo embed URL (takes priority over image)', max_length=500),
        ),
    ]
