# Generated by Django 5.2.9 on 2026-02-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_hero_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='image_position',
            field=models.CharField(choices=[('left', 'Image Left, Text Right'), ('right', 'Image Right, Text Left')], default='left', help_text='Only applies to Two Column section type', max_length=10),
        ),
    ]
