# Generated by Django 5.2.9 on 2026-02-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_pagesection_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='image',
            field=models.ImageField(blank=True, help_text='🔹 TWO COLUMN ONLY - Leave blank for Text Block, Features Grid, and CTA sections', null=True, upload_to='pages/sections/'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='image_position',
            field=models.CharField(choices=[('left', 'Image Left, Text Right'), ('right', 'Image Right, Text Left')], default='left', help_text='🔹 TWO COLUMN ONLY - Choose image placement (ignored for other section types)', max_length=10),
        ),
    ]
