# Generated by Django 5.2.9 on 2026-02-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_pagesection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='admin_note',
            field=models.CharField(default='Images are ONLY used for Two Column sections. Images will NOT show for Text, Features, or CTA sections.', editable=False, max_length=255),
        ),
    ]
