# Generated by Django 5.2.9 on 2026-02-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_pagesection_admin_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_url',
            field=models.URLField(blank=True, help_text='Auto-detected from this site. Only change if using a custom domain.', verbose_name='Site URL'),
        ),
    ]
