# Generated by Django 6.0 on 2026-02-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_sitesettings_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', help_text='Enter your GA4 Measurement ID (e.g. G-XXXXXXXXXX)', max_length=30, verbose_name='Google Analytics GA4 ID'),
        ),
    ]
