# Generated by Django 6.0 on 2026-02-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_sitesettings_google_analytics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_search_console_verification',
            field=models.CharField(blank=True, default='', help_text='Enter the content value from Google Search Console meta tag verification.', max_length=255, verbose_name='Google Search Console Verification Code'),
        ),
    ]
