# Generated by Django 5.2.9 on 2026-03-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('pages', '0018_sitesettings_google_search_console_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_container',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to='content.contentcontainer'),
        ),
    ]
