# Generated by Django 5.2.9 on 2026-03-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('pages', '0020_create_page_containers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content_container',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='content.contentcontainer'),
        ),
    ]
