# Generated by Django 5.2.9 on 2026-03-02 13:22
from django.db import migrations


def migrate_page_faq_to_content(apps, schema_editor):
    PageFAQBlock = apps.get_model("pages", "FAQBlock")
    PageFAQItem = apps.get_model("pages", "FAQItem")

    ContentFAQBlock = apps.get_model("content", "FAQBlock")
    ContentFAQItem = apps.get_model("content", "FAQItem")

    for old_block in PageFAQBlock.objects.all():
        page = old_block.page
        container = page.content_container

        # Create new FAQBlock
        new_block = ContentFAQBlock.objects.create(
            container=container,
            title=old_block.title,
            order=old_block.order,
            published=old_block.published,
        )

        # Copy items
        for old_item in old_block.items.all():
            ContentFAQItem.objects.create(
                faq_block=new_block,
                question=old_item.question,
                answer=old_item.answer,
                order=old_item.order,
                published=old_item.published,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0021_alter_page_content_container"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_page_faq_to_content, migrations.RunPython.noop),
    ]
