# Generated by Django 5.2.9 on 2026-03-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_migrate_page_faq_to_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqitem',
            name='faq_block',
        ),
        migrations.DeleteModel(
            name='FAQBlock',
        ),
        migrations.DeleteModel(
            name='FAQItem',
        ),
    ]
