# Generated by Django 5.2.9 on 2026-03-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_delete_threecolumnblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageSection',
        ),
    ]
