# Generated by Django 5.2.9 on 2026-03-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_delete_pagesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='page',
        ),
        migrations.DeleteModel(
            name='HeroBanner',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
