# Generated by Django 5.2.9 on 2026-03-02 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_heroblock_banner_action_link_and_more'),
        ('pages', '0026_remove_hero_page_delete_herobanner_delete_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryblock',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_blocks', to='content.contentcontainer'),
        ),
    ]
