# Generated by Django 5.2.9 on 2026-03-02 19:44
from django.db import migrations


def forwards(apps, schema_editor):
    GalleryBlock = apps.get_model("pages", "GalleryBlock")
    Page = apps.get_model("pages", "Page")

    for gallery in GalleryBlock.objects.all():
        if gallery.page and gallery.page.content_container:
            gallery.container = gallery.page.content_container
            gallery.save(update_fields=["container"])


def backwards(apps, schema_editor):
    # Optional reverse (not strictly needed)
    GalleryBlock = apps.get_model("pages", "GalleryBlock")

    for gallery in GalleryBlock.objects.all():
        gallery.container = None
        gallery.save(update_fields=["container"])


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0027_galleryblock_container"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
