# Generated by Django 5.2.9 on 2026-03-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_migrate_gallery_to_container'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='GalleryBlock',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
