# Generated by Django 5.2.9 on 2025-12-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='introduction',
        ),
    ]
