# Generated by Django 5.2.9 on 2025-12-27 13:56

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=blog.models.get_default_category, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
    ]
