# Generated by Django 5.2.9 on 2026-01-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='External URL for product image (jpg/png/webp only)', max_length=500, null=True),
        ),
    ]
