# Generated by Django 6.0 on 2025-12-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
    ]
