# Generated by Django 6.0 on 2025-12-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_video_file_remove_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (watch or youtu.be)', null=True),
        ),
    ]
