# Generated by Django 5.2.9 on 2025-12-27 13:56

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=shop.models.get_default_category, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category'),
        ),
    ]
