# Generated by Django 5.2.9 on 2025-12-31 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_number_of_pages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to Our Shop', help_text='Main heading in the hero section.', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Smaller text above or below the title.', max_length=300)),
                ('hero_body', models.TextField(blank=True, help_text='Optional descriptive text for the hero.', null=True)),
                ('hero_image', models.ImageField(blank=True, help_text='Background or side image for the hero section.', null=True, upload_to='shop/hero/')),
                ('hero_button_text', models.CharField(blank=True, help_text="e.g. 'Browse Products', 'Shop Now'", max_length=100)),
                ('hero_button_link', models.CharField(blank=True, help_text='URL or anchor link for the button (e.g. #products or /shop/category/sale/)', max_length=200)),
                ('show_intro_section', models.BooleanField(default=False, help_text='Display an intro text block below the hero.')),
                ('intro_title', models.CharField(blank=True, max_length=200)),
                ('intro_body', models.TextField(blank=True, help_text='Rich text introduction to your shop.', null=True)),
                ('show_spotlight', models.BooleanField(default=False, help_text='Display a featured product or promotion section.')),
                ('spotlight_title', models.CharField(blank=True, max_length=200)),
                ('spotlight_body', models.TextField(blank=True, null=True)),
                ('spotlight_image', models.ImageField(blank=True, null=True, upload_to='shop/spotlight/')),
                ('spotlight_button_text', models.CharField(blank=True, max_length=100)),
                ('spotlight_button_link', models.CharField(blank=True, max_length=200)),
                ('spotlight_image_position', models.CharField(choices=[('left', 'Image Left, Text Right'), ('right', 'Image Right, Text Left')], default='right', max_length=10)),
                ('products_per_page', models.PositiveIntegerField(default=12, help_text='Number of products to show per page.')),
                ('product_display_mode', models.CharField(choices=[('all', 'All Products'), ('featured', 'Featured Products Only'), ('category', 'Specific Category')], default='all', max_length=20)),
                ('show_promo_blocks', models.BooleanField(default=False, help_text='Display promotional column blocks on the shop homepage.')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('display_category', models.ForeignKey(blank=True, help_text="Only used when display mode is 'Specific Category'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
            ],
            options={
                'verbose_name': 'Shop Settings',
                'verbose_name_plural': 'Shop Settings',
            },
        ),
        migrations.CreateModel(
            name='ShopPromoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('col_1_title', models.CharField(blank=True, max_length=150)),
                ('col_1_image', models.ImageField(blank=True, null=True, upload_to='shop/promo/')),
                ('col_1_body', models.TextField(blank=True, null=True)),
                ('col_2_title', models.CharField(blank=True, max_length=150)),
                ('col_2_image', models.ImageField(blank=True, null=True, upload_to='shop/promo/')),
                ('col_2_body', models.TextField(blank=True, null=True)),
                ('col_3_title', models.CharField(blank=True, max_length=150)),
                ('col_3_image', models.ImageField(blank=True, null=True, upload_to='shop/promo/')),
                ('col_3_body', models.TextField(blank=True, null=True)),
                ('shop_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_blocks', to='shop.shopsettings')),
            ],
            options={
                'verbose_name': 'Shop Promo Block',
                'verbose_name_plural': 'SHOP PROMO BLOCKS',
                'ordering': ['order'],
            },
        ),
    ]
