# Generated by Django 5.2.9 on 2025-12-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shopsettings_shoppromoblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='intro_order',
            field=models.PositiveIntegerField(default=1, help_text='Display order for intro section (lower numbers appear first).'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='promo_blocks_order',
            field=models.PositiveIntegerField(default=2, help_text='Display order for promo blocks section.'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='spotlight_order',
            field=models.PositiveIntegerField(default=3, help_text='Display order for spotlight section.'),
        ),
    ]
