# Generated by Django 5.2.9 on 2026-01-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shopsettings_intro_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Side image for the hero section.', null=True, upload_to='shop/hero/'),
        ),
    ]
