# Generated by Django 5.2.9 on 2026-01-24 07:51

import shop.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_shopsettings_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='email_from_address',
            field=models.EmailField(blank=True, default='', help_text='Default sender address for outgoing emails', max_length=254, verbose_name='From Email Address'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='email_host',
            field=models.CharField(blank=True, default='', help_text='e.g., smtp.gmail.com, smtp.sendgrid.net', max_length=255, verbose_name='SMTP Host'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='email_host_password',
            field=shop.fields.EncryptedCharField(blank=True, default='', help_text='Your SMTP password or app password (encrypted at rest)', max_length=500, verbose_name='SMTP Password'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='email_host_user',
            field=models.CharField(blank=True, default='', help_text='Your SMTP username or email address', max_length=255, verbose_name='SMTP Username'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587, help_text='Usually 587 (TLS) or 465 (SSL)', verbose_name='SMTP Port'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Enable TLS encryption (recommended)', verbose_name='Use TLS'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='stripe_live_mode',
            field=models.BooleanField(default=False, help_text='Enable for production payments. Disable for test mode.', verbose_name='Stripe Live Mode'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='stripe_public_key',
            field=models.CharField(blank=True, default='', help_text='pk_test_... or pk_live_... (falls back to .env if empty)', max_length=255, verbose_name='Stripe Public Key'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='stripe_secret_key',
            field=shop.fields.EncryptedCharField(blank=True, default='', help_text='sk_test_... or sk_live_... (encrypted at rest)', max_length=500, verbose_name='Stripe Secret Key'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='stripe_webhook_secret',
            field=shop.fields.EncryptedCharField(blank=True, default='', help_text='whsec_... (encrypted at rest)', max_length=500, verbose_name='Stripe Webhook Secret'),
        ),
    ]
