# Generated by Django 5.2.9 on 2026-02-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_add_encrypted_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='is_demo_site',
            field=models.BooleanField(default=False, help_text='Enable for sites being built for sale. Disables Stripe payments until configured by buyer.', verbose_name='Demo Site Mode'),
        ),
    ]
