# Generated by Django 5.2.9 on 2026-02-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_shopsettings_is_demo_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='show_products_on_homepage',
            field=models.BooleanField(default=True, help_text='Display product grid on shop homepage. Turn off if using only spotlight/promo sections.'),
        ),
    ]
