# Generated by Django 5.2.9 on 2026-02-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_shopsettings_show_products_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='layout_mode',
            field=models.CharField(choices=[('standard', 'Standard Layout'), ('landing', 'Landing Layout (No Header/Footer)')], default='standard', max_length=20),
        ),
    ]
