# Generated by Django 5.2.9 on 2026-02-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_layout_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='faq_order',
            field=models.PositiveIntegerField(default=4, help_text='Display order for FAQ section.'),
        ),
        migrations.CreateModel(
            name='ShopFAQBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Optional section title like 'Frequently Asked Questions'", max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('shop_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_blocks', to='shop.shopsettings')),
            ],
            options={
                'verbose_name': 'Shop FAQ Block',
                'verbose_name_plural': 'SHOP FAQ BLOCKS',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShopFAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('faq_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shopfaqblock')),
            ],
            options={
                'verbose_name': 'Shop FAQ Item',
                'verbose_name_plural': 'Shop FAQ Items',
                'ordering': ['order'],
            },
        ),
    ]
