# Generated by Django 5.2.9 on 2026-02-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_shopsettings_faq_order_shopfaqblock_shopfaqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='products_order',
            field=models.PositiveIntegerField(default=99, help_text='Display order for product grid section.'),
        ),
    ]
