# Generated by Django 5.2.9 on 2026-03-02 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('shop', '0014_shopsettings_products_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='content_container',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_settings', to='content.contentcontainer'),
        ),
    ]
