# Generated by Django 5.2.9 on 2026-03-02 13:03
from django.db import migrations


def create_shop_container(apps, schema_editor):
    ShopSettings = apps.get_model("shop", "ShopSettings")
    ContentContainer = apps.get_model("content", "ContentContainer")

    for shop_settings in ShopSettings.objects.all():
        if shop_settings.content_container_id is None:
            container = ContentContainer.objects.create(name="Shop Settings Container")
            shop_settings.content_container = container
            shop_settings.save(update_fields=["content_container"])


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0015_shopsettings_content_container"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_shop_container, migrations.RunPython.noop),
    ]
