# Generated by Django 5.2.9 on 2026-03-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('shop', '0016_create_shop_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='content_container',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_settings', to='content.contentcontainer'),
        ),
    ]
