# Generated by Django 5.2.9 on 2026-03-02 13:32

from django.db import migrations


def migrate_shop_faq_to_content(apps, schema_editor):
    ShopFAQBlock = apps.get_model("shop", "ShopFAQBlock")
    ShopFAQItem = apps.get_model("shop", "ShopFAQItem")

    ContentFAQBlock = apps.get_model("content", "FAQBlock")
    ContentFAQItem = apps.get_model("content", "FAQItem")

    for old_block in ShopFAQBlock.objects.all():
        shop_settings = old_block.shop_settings
        container = shop_settings.content_container

        new_block = ContentFAQBlock.objects.create(
            container=container,
            title=old_block.title,
            order=old_block.order,
            published=old_block.published,
        )

        for old_item in old_block.items.all():
            ContentFAQItem.objects.create(
                faq_block=new_block,
                question=old_item.question,
                answer=old_item.answer,
                order=old_item.order,
                published=old_item.published,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0017_alter_shopsettings_content_container"),
        ("content", "0002_faqblock_faqitem"),
    ]

    operations = [
        migrations.RunPython(migrate_shop_faq_to_content, migrations.RunPython.noop),
    ]
