# Generated by Django 5.2.9 on 2026-03-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_migrate_shop_faq_to_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopfaqitem',
            name='faq_block',
        ),
        migrations.DeleteModel(
            name='ShopFAQBlock',
        ),
        migrations.DeleteModel(
            name='ShopFAQItem',
        ),
    ]
