# Generated by Django 5.2.9 on 2026-03-02 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0020_delete_shoppromoblock"),
        ("content", "0010_migrate_shop_spotlight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopsettings",
            name="show_spotlight",
        ),
        migrations.RemoveField(
            model_name="shopsettings",
            name="spotlight_body",
        ),
        migrations.RemoveField(
            model_name="shopsettings",
            name="spotlight_button_link",
        ),
        migrations.RemoveField(
            model_name="shopsettings",
            name="spotlight_button_text",
        ),
        migrations.RemoveField(
            model_name="shopsettings",
            name="spotlight_image",
        ),
        migrations.RemoveField(
            model_name="shopsettings",
            name="spotlight_image_position",
        ),
        migrations.RemoveField(
            model_name="shopsettings",
            name="spotlight_order",
        ),
        migrations.RemoveField(
            model_name="shopsettings",
            name="spotlight_title",
        ),
    ]
