# Generated by Django 5.2.9 on 2026-03-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_shopsettings_show_spotlight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='hero_body',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='hero_button_link',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='hero_button_text',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='hero_title',
        ),
    ]
