# Generated by Django 5.2.9 on 2026-03-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_shopsettings_hero_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='faq_order',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='intro_body',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='intro_order',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='intro_title',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='promo_blocks_order',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='show_intro_section',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='show_promo_blocks',
        ),
    ]
