# Generated by Django 5.2.9 on 2026-03-02 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Optional section title like 'Frequently Asked Questions'", max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_blocks', to='content.contentcontainer')),
            ],
            options={
                'verbose_name': 'FAQ Block',
                'verbose_name_plural': 'FAQ Blocks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('faq_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.faqblock')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order'],
            },
        ),
    ]
