# Generated by Django 5.2.9 on 2026-03-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_faqblock_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeColumnBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('col_1_title', models.CharField(blank=True, max_length=255)),
                ('col_1_image', models.ImageField(blank=True, null=True, upload_to='three_columns/')),
                ('col_1_body', models.TextField(blank=True)),
                ('col_2_title', models.CharField(blank=True, max_length=255)),
                ('col_2_image', models.ImageField(blank=True, null=True, upload_to='three_columns/')),
                ('col_2_body', models.TextField(blank=True)),
                ('col_3_title', models.CharField(blank=True, max_length=255)),
                ('col_3_image', models.ImageField(blank=True, null=True, upload_to='three_columns/')),
                ('col_3_body', models.TextField(blank=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_column_blocks', to='content.contentcontainer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
