# Generated by Django 5.2.9 on 2026-03-02 14:15

from django.db import migrations


def migrate_page_three_columns(apps, schema_editor):
    PageThreeColumn = apps.get_model("pages", "ThreeColumnBlock")
    ContentThreeColumn = apps.get_model("content", "ThreeColumnBlock")

    for old_block in PageThreeColumn.objects.all():
        page = old_block.page
        container = page.content_container

        ContentThreeColumn.objects.create(
            container=container,
            order=old_block.order,
            published=old_block.published,
            col_1_title=old_block.col_1_title,
            col_1_image=old_block.col_1_image,
            col_1_body=old_block.col_1_body,
            col_2_title=old_block.col_2_title,
            col_2_image=old_block.col_2_image,
            col_2_body=old_block.col_2_body,
            col_3_title=old_block.col_3_title,
            col_3_image=old_block.col_3_image,
            col_3_body=old_block.col_3_body,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_threecolumnblock"),
        ("pages", "0023_remove_faqitem_faq_block_delete_faqblock_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_page_three_columns, migrations.RunPython.noop),
    ]
