# Generated by Django 5.2.9 on 2026-03-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_migrate_shop_promo_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'Text Block'), ('two_column', 'Two Column'), ('features', 'Features Grid'), ('cta', 'Call to Action')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('image_position', models.CharField(choices=[('left', 'Image Left, Text Right'), ('right', 'Image Right, Text Left')], default='left', max_length=10)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.URLField(blank=True)),
                ('col_1_body', models.TextField(blank=True, null=True)),
                ('col_2_body', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.contentcontainer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
