# Generated by Django 5.2.9 on 2026-03-02 15:05

from django.db import migrations


def migrate_page_sections(apps, schema_editor):
    PageSection = apps.get_model("pages", "PageSection")
    Page = apps.get_model("pages", "Page")
    SectionBlock = apps.get_model("content", "SectionBlock")

    for section in PageSection.objects.all():
        try:
            page = section.page
            container = page.content_container
        except Exception:
            continue

        SectionBlock.objects.create(
            container=container,
            section_type=section.section_type,
            title=section.title,
            subtitle=section.subtitle,
            body=section.body,
            image=section.image,
            image_position=section.image_position,
            button_text=section.button_text,
            button_link=section.button_link,
            col_1_body=section.col_1_body,
            col_2_body=section.col_2_body,
            order=section.order,
            published=section.published,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_sectionblock"),
        ("pages", "0023_remove_faqitem_faq_block_delete_faqblock_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_page_sections),
    ]
