# Generated by Django 5.2.9 on 2026-03-02 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_migrate_page_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('intro_text', models.TextField(blank=True)),
                ('embed_html', models.TextField(help_text='Paste your email provider embed HTML here.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_blocks', to='content.contentcontainer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
