# Generated by Django 5.2.9 on 2026-03-02 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_newsletterblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotlightBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='spotlight/')),
                ('image_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=10)),
                ('button_text', models.CharField(blank=True, max_length=255)),
                ('button_link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotlight_blocks', to='content.contentcontainer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
