# Generated by Django 5.2.9 on 2026-03-02 16:10

from django.db import migrations


def migrate_shop_spotlight(apps, schema_editor):
    ShopSettings = apps.get_model("shop", "ShopSettings")
    SpotlightBlock = apps.get_model("content", "SpotlightBlock")

    for shop in ShopSettings.objects.all():
        # Only create SpotlightBlock if spotlight is configured
        has_content = any(
            [
                shop.spotlight_title,
                shop.spotlight_body,
                shop.spotlight_image,
                shop.spotlight_button_text,
                shop.spotlight_button_link,
            ]
        )

        if not has_content and not shop.show_spotlight:
            continue

        SpotlightBlock.objects.create(
            container=shop.content_container,
            title=shop.spotlight_title or "",
            body=shop.spotlight_body or "",
            image=shop.spotlight_image,
            image_position=shop.spotlight_image_position,
            button_text=shop.spotlight_button_text or "",
            button_link=shop.spotlight_button_link or "",
            order=shop.spotlight_order,
            published=shop.show_spotlight,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_spotlightblock"),
        ("shop", "0020_delete_shoppromoblock"),
    ]

    operations = [
        migrations.RunPython(migrate_shop_spotlight, migrations.RunPython.noop),
    ]
