# Generated by Django 5.2.9 on 2026-03-02 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_migrate_shop_spotlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube URL')),
                ('button_text', models.CharField(blank=True, max_length=255)),
                ('button_link', models.URLField(blank=True)),
                ('banner_text', models.CharField(blank=True, max_length=255)),
                ('banner_action_text', models.CharField(blank=True, max_length=255)),
                ('banner_action_link', models.URLField(blank=True)),
                ('banner_badge_text', models.CharField(blank=True, max_length=100)),
                ('banner_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_blocks', to='content.contentcontainer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
