# Generated by Django 5.2.9 on 2026-03-02 18:23

from django.db import migrations


def migrate_page_heroes(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    OldHero = apps.get_model("pages", "Hero")
    OldHeroBanner = apps.get_model("pages", "HeroBanner")
    HeroBlock = apps.get_model("content", "HeroBlock")

    # Get active banner (global system)
    active_banner = OldHeroBanner.objects.filter(is_active=True).first()

    for page in Page.objects.all():
        if not hasattr(page, "content_container") or not page.content_container:
            continue

        old_heroes = OldHero.objects.filter(page=page)

        for hero in old_heroes:
            HeroBlock.objects.create(
                container=page.content_container,
                title=hero.title,
                subtitle=hero.subtitle,
                body=hero.body,
                image=hero.image,
                video_url=hero.video_url,
                button_text=hero.button_text,
                button_link=hero.button_link,
                order=hero.order,
                published=hero.is_active,
                # Banner fields (copied from global banner)
                banner_text=active_banner.text if active_banner else "",
                banner_action_text=active_banner.action_text if active_banner else "",
                banner_action_link=active_banner.action_link if active_banner else "",
                banner_badge_text=active_banner.badge_text if active_banner else "",
                banner_published=active_banner.is_active if active_banner else False,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_heroblock"),
        ("pages", "0025_delete_pagesection"),
    ]

    operations = [
        migrations.RunPython(migrate_page_heroes, migrations.RunPython.noop),
    ]
