# Generated by Django 5.2.9 on 2026-03-02 18:27

from django.db import migrations


def migrate_shop_hero(apps, schema_editor):
    ShopSettings = apps.get_model("shop", "ShopSettings")
    HeroBlock = apps.get_model("content", "HeroBlock")

    for shop in ShopSettings.objects.all():
        if not shop.content_container:
            continue

        has_content = any(
            [
                shop.hero_title,
                shop.hero_subtitle,
                shop.hero_body,
                shop.hero_image,
                shop.hero_button_text,
                shop.hero_button_link,
            ]
        )

        if not has_content:
            continue

        HeroBlock.objects.create(
            container=shop.content_container,
            title=shop.hero_title or "",
            subtitle=shop.hero_subtitle or "",
            body=shop.hero_body or "",
            image=shop.hero_image,
            video_url="",  # Shop did not support video
            button_text=shop.hero_button_text or "",
            button_link=shop.hero_button_link or "",
            order=0,
            published=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0012_migrate_page_hero_to_container"),
        ("shop", "0021_remove_shopsettings_show_spotlight_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_shop_hero, migrations.RunPython.noop),
    ]
