# Generated by Django 5.2.9 on 2026-03-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_migrate_shop_hero_to_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroblock',
            name='banner_action_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='banner_action_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='banner_badge_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='banner_published',
            field=models.BooleanField(default=False, help_text='Enable banner above hero title.'),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='banner_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Side or background image for the hero section.', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube embed URL (takes priority over image)', max_length=500),
        ),
    ]
