# Generated by Django 5.2.9 on 2026-03-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_galleryblock_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroblock',
            name='banner_action_link',
            field=models.URLField(blank=True, help_text='URL the banner link should go to. Required if link text is provided.'),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='banner_action_text',
            field=models.CharField(blank=True, help_text="Clickable link text displayed on the right (e.g. 'Read More').", max_length=100),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='banner_badge_text',
            field=models.CharField(blank=True, help_text="Small label shown on the left of the banner (e.g. 'New', 'Update', 'Featured').", max_length=50),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='banner_text',
            field=models.CharField(blank=True, help_text='Main banner message displayed in the centre of the banner.', max_length=200),
        ),
    ]
