# Generated by Django 5.2.9 on 2026-03-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_heroblock_banner_action_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='pages/gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='pages/gallery/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='heroblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Side or background image for the hero section.', null=True, upload_to='pages/hero/'),
        ),
        migrations.AlterField(
            model_name='sectionblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/sections/'),
        ),
        migrations.AlterField(
            model_name='spotlightblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/spotlight/'),
        ),
        migrations.AlterField(
            model_name='threecolumnblock',
            name='col_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/columns/'),
        ),
        migrations.AlterField(
            model_name='threecolumnblock',
            name='col_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/columns/'),
        ),
        migrations.AlterField(
            model_name='threecolumnblock',
            name='col_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/columns/'),
        ),
    ]
