# Generated by Django 5.2.9 on 2026-03-05 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkHubBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='Paste YouTube Watch URL. It will display at the top of the page.')),
                ('primary_link', models.PositiveIntegerField(default=0, help_text='Enter the number of the link to highlight with the primary background (1 = first link, 2 = second link, etc).')),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkhub_blocks', to='content.contentcontainer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LinkHubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='linkhub/items/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content.linkhubblock')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='linkhubblock',
            constraint=models.UniqueConstraint(fields=('container', 'slug'), name='unique_slug_per_container'),
        ),
    ]
