# Generated by Django 5.2.9 on 2026-03-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_linkhubblock_linkhubitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkhubblock',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Optional logo displayed above the LinkHub title.', null=True, upload_to='linkhub/logo/', verbose_name='Logo Image'),
        ),
    ]
