# Generated by Django 5.2.9 on 2026-03-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_linkhubblock_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterblock',
            name='embed_html',
            field=models.TextField(blank=True, help_text='Paste your newsletter provider embed code here.'),
        ),
    ]
